name: Release Extension

on:
  push:
    tags:
      - 'v*' # 当推送 v 开头的标签时触发

permissions:
  contents: write # 添加写入权限

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整的 git 历史用于生成更新日志

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build:all

      - name: Create ZIP file
        run: |
          cd dist
          zip -r ../chrome-bookmark-manager-${{ env.VERSION }}.zip *
          cd ..

      - name: Install crx package
        run: npm install -g crx

      - name: Generate private key
        run: |
          echo "${{ secrets.EXTENSION_PRIVATE_KEY }}" > private.pem
        env:
          EXTENSION_PRIVATE_KEY: ${{ secrets.EXTENSION_PRIVATE_KEY }}

      - name: Package CRX
        run: |
          crx pack dist \
            -o chrome-bookmark-manager-${{ env.VERSION }}.crx \
            -p private.pem

      - name: Verify files exist
        run: |
          ls -la chrome-bookmark-manager-${{ env.VERSION }}.zip
          ls -la chrome-bookmark-manager-${{ env.VERSION }}.crx

      - name: Cleanup private key
        run: rm -f private.pem

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.VERSION }}
          files: |
            chrome-bookmark-manager-${{ env.VERSION }}.zip
            chrome-bookmark-manager-${{ env.VERSION }}.crx
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}